# Generated by Django 4.2.2 on 2023-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=20)),
                ('restaurant_id', models.IntegerField(null=True)),
                ('itemDescription', models.TextField()),
                ('itemType', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itemImage', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='restaurantRegister',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantAddress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('cuisineType', models.CharField(max_length=50)),
                ('createdBy', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restaurant_info',
            },
        ),
    ]
